Add Logotype
hedgedoc/hedgedoc-logo pull request #3
Opened 2020-09-29 09:20 UTC by ericgaspar

2020-09-30 09:19 UTC, ccoenen commented
this looks fantastic. One question I have is: would you like to define a guideline for "weird" backgrounds, say when a background is close to brown anyway (and the hedgehog would have very little contrast) or when it is an odd hue like fuchsia (and the colour version might look weird on it).

Many styleguides not only define what is "good", but also what is discouraged. For example the pragmatic and ugly solution to the first example would be a red outline or glow, which I think should be discouraged. Example from UPS:

![UPS Brand Guideline don'ts](https://user-images.githubusercontent.com/124909/94667072-9d650180-030e-11eb-8dc3-3017e86daf33.png)

I'm not asking to copy these three specifically, these are just examples.

One last request would be a favicon-sized variant (I know they are huge nowadays, but what I really mean is a variant that works at ~16x16 px)

2020-09-30 09:22 UTC, mrdrogdrog commented
Great 👌


Can you please copy the font url and the color codes into the readme.md or an extra text file?

2020-09-30 10:30 UTC, mrdrogdrog commented
We also still need a license that says "free use but only in connection with unmodified software from $github_organisation_url"

2020-09-30 13:50 UTC, mrdrogdrog commented
@ccoenen  IMHO an extra favicon version is not needed. 
![image](https://user-images.githubusercontent.com/6124140/94693978-a49f0600-0334-11eb-8418-b5bd47ae4d8f.png)

2020-09-30 14:11 UTC, ccoenen commented
Tiny logo variant could, for example, skip the white reflections in the eyes. And it could have less "spikes" (by count of spikes) so that they don't form a circle but retain their spikiness at tiny resolutions. Or they could be cutting deeper into the body.

The point of these variations is, that visual consistency is more important than actual consistency. So, while this is a perfect scaled version of the original, it really looks like a circle (especially on the dark background).

2020-09-30 14:13 UTC, ericgaspar commented
![Capture d’écran 9](https://user-images.githubusercontent.com/46165813/94696901-d9608c80-0337-11eb-8fa0-7ae0e7c2b462.png)

2020-09-30 14:16 UTC, mrdrogdrog commented
I'm not sure if the smaller versions should skip the reflection in the eyes. IMHO without the reflection the eyes are a bit.. creepy :s

2020-09-30 14:17 UTC, ericgaspar commented
![Capture d’écran 13](https://user-images.githubusercontent.com/46165813/94697377-6d325880-0338-11eb-9ed8-24a69dfaa5e7.png)

2020-09-30 14:22 UTC, mrdrogdrog commented
https://github.com/codimd/hedgedoc-logo/pull/3#issuecomment-701420690

don't forget to add this to the git.

2020-10-01 18:15 UTC, mrdrogdrog requested changes

2020-10-01 18:15 UTC, mrdrogdrog commented on GUIDELINES.md
> +
Still need a license that says: "Can be used for free in combination with unmodified software from https://github.com/codimd", or something like that.

2020-10-01 18:19 UTC, mrdrogdrog commented on GUIDELINES.md
> +
(This is an general issue, that hasn't to solved by yourself. I don't want us to forget it :sweat_smile: )

2020-11-04 20:56 UTC, mrdrogdrog commented
Just for reference:

[Complete preview](https://github.com/ericgaspar/hedgedoc-logo)

2020-11-08 13:29 UTC, mrdrogdrog approved these changes
❤️

2020-11-08 13:50 UTC, DerMolly approved these changes

2020-11-08 15:29 UTC, ErikMichelson approved these changes

2020-11-08 19:46 UTC, merged